export const FACEBOOK = 'FACEBOOK'
export const GOOGLE = 'GOOGLE'
export const FBSIGNIN_CANCELLED = 'FBSIGNIN_CANCELLED'
export const GOOGLE_SIGNIN_CANCEL_ERROR_CODE = '-5'
export const CHECK_YOUR_EMAIL_AND_PASSWORD_MESSAGE = 'Check your email and password'
